services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: change_me
    volumes:
      - mongodata:/data/db

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:8080"
    environment:
      HTTP_SERVER_HOST: "0.0.0.0"
      HTTP_SERVER_PORT: "8080"
      HTTP_SERVER_READ_TIMEOUT: "5s"
      HTTP_SERVER_READ_HEADER_TIMEOUT: "5s"
      HTTP_SERVER_WRITE_TIMEOUT: "5s"
      HTTP_SERVER_IDLE_TIMEOUT: "5s"
      DB_URI: "mongodb://root:change_me@mongo:27017/admin"
      LOGGING: True
volumes:
  mongodata:
